import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  card: {
    border: '1px solid var(--border)',
    borderRadius: 8,
    overflow: 'hidden',
    margin: '12px 0',
  },
  header: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '12px 14px',
    background: 'var(--bg-1)',
    border: 'none',
    cursor: 'pointer',
    color: 'var(--text-1)',
  },
  iconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    background: '#f0fdf4',
    border: '1px solid #bbf7d0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  title: {
    fontSize: 14,
    fontWeight: 600,
    color: 'var(--text-1)',
  },
  viewText: {
    fontSize: 12,
    color: 'var(--primary)',
    fontWeight: 600,
    flexShrink: 0,
  },
  fileRow: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '9px 14px',
    border: 'none',
    borderBottom: '1px solid var(--bg-2)',
    background: 'transparent',
    cursor: 'pointer',
    transition: 'background 0.1s',
    textAlign: 'left',
  },
  badge: {
    width: 20,
    height: 20,
    borderRadius: 4,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 10,
    fontWeight: 700,
    flexShrink: 0,
  },
  filePath: {
    flex: 1,
    fontSize: 13,
    color: 'var(--text-2)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  fileStat: {
    fontSize: 12,
    display: 'flex',
    gap: 6,
    flexShrink: 0,
  },
  diffPanel: {
    background: '#0f172a',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 12,
    lineHeight: 1.7,
    overflowX: 'auto',
    maxHeight: 420,
    overflowY: 'auto',
  },
  diffHunkHeader: {
    padding: '6px 14px',
    color: '#64748b',
    background: '#1e293b',
    fontSize: 11,
  },
  diffSegmentHeader: {
    padding: '5px 14px',
    color: '#94a3b8',
    background: '#111827',
    fontSize: 11,
  },
  diffLine: {
    padding: '1px 14px 1px 48px',
    position: 'relative',
    whiteSpace: 'pre',
  },
  diffLineNum: {
    position: 'absolute',
    left: 0,
    width: 44,
    textAlign: 'right',
    paddingRight: 8,
    color: '#475569',
    fontSize: 11,
    userSelect: 'none',
  },
  diffAdd: {
    background: 'rgba(22,163,74,0.15)',
    color: '#86efac',
  },
  diffDel: {
    background: 'rgba(220,38,38,0.15)',
    color: '#fca5a5',
  },
  diffCtx: {
    color: '#94a3b8',
  },
  compactRoot: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '4px 10px',
    borderRadius: 6,
    background: 'var(--bg-2)',
    marginTop: 4,
  },
  errorText: {
    padding: '8px 14px',
    color: 'var(--red)',
    fontSize: 13,
  },
  loadingText: {
    padding: '8px 14px',
    color: 'var(--text-3)',
    fontSize: 13,
  },
}
