import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,.35)',
    zIndex: 1000,
    display: 'flex',
    alignItems: 'flex-end',
  },
  sheet: {
    width: '100%',
    maxHeight: '82vh',
    display: 'flex',
    flexDirection: 'column',
    background: 'var(--bg-card)',
    borderRadius: '16px 16px 0 0',
  },
  sheetHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '14px 16px 10px',
    borderBottom: '1px solid var(--border-light)',
    flexShrink: 0,
  },
  titleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  sheetTitle: {
    fontWeight: 600,
    fontSize: 16,
  },
  closeBtn: {
    width: 30,
    height: 30,
    fontSize: 22,
    color: 'var(--text-muted)',
    background: 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  body: {
    padding: '12px 16px',
    overflowY: 'auto',
    flex: 1,
    minHeight: 0,
  },
  fieldGroup: {
    marginBottom: 16,
  },
  fieldLabel: {
    fontSize: 12,
    color: 'var(--text-muted)',
    marginBottom: 6,
    fontWeight: 500,
  },
  agentSelector: {
    width: '100%',
    minHeight: 44,
    padding: '0 12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    background: 'var(--bg)',
    border: '1px solid var(--border-light)',
    borderRadius: 8,
    fontSize: 15,
    color: 'var(--text-primary)',
    textAlign: 'left',
  },
  agentSelectorText: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  dropdown: {
    marginTop: 4,
    background: 'var(--bg-card)',
    border: '1px solid var(--border-light)',
    borderRadius: 8,
    overflow: 'hidden',
    maxHeight: 240,
    overflowY: 'auto',
  },
  dropdownEmpty: {
    padding: '16px 12px',
    fontSize: 14,
    color: 'var(--text-muted)',
    textAlign: 'center',
  },
  dropdownItem: {
    width: '100%',
    padding: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    fontSize: 15,
    color: 'var(--text-primary)',
    textAlign: 'left',
    borderBottom: '1px solid var(--border-light)',
  },
  dropdownItemActive: {
    background: 'rgba(0,0,0,0.03)',
  },
  dropdownItemName: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  radioRow: {
    display: 'flex',
    gap: 8,
  },
  radio: {
    flex: 1,
    minHeight: 44,
    padding: '0 12px',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    background: 'var(--bg)',
    border: '1px solid var(--border-light)',
    borderRadius: 8,
    fontSize: 14,
    color: 'var(--text-primary)',
  },
  radioActive: {
    border: '1px solid var(--primary)',
    color: 'var(--primary)',
    background: 'var(--bg-card)',
  },
  radioDot: {
    width: 16,
    height: 16,
    borderRadius: '50%',
    border: '1.5px solid var(--border-light)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  radioDotInner: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: 'var(--primary)',
  },
  templateSection: {
    marginBottom: 16,
  },
  templateList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    background: 'var(--bg)',
    border: '1px solid var(--border-light)',
    borderRadius: 8,
    overflow: 'hidden',
  },
  loading: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '28px 0',
    justifyContent: 'center',
    color: 'var(--text-muted)',
    fontSize: 14,
  },
  empty: {
    padding: '40px 0',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 8,
    color: 'var(--text-muted)',
  },
  emptyText: {
    fontSize: 14,
  },
  error: {
    margin: '12px 16px',
    padding: '10px 12px',
    borderRadius: 8,
    background: 'rgba(250,81,81,0.08)',
    color: 'var(--error)',
    fontSize: 13,
  },
  templateItem: {
    width: '100%',
    padding: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    textAlign: 'left',
    borderBottom: '1px solid var(--border-light)',
  },
  templateBody: {
    flex: 1,
    minWidth: 0,
  },
  templateName: {
    fontSize: 15,
    fontWeight: 600,
    color: 'var(--text-primary)',
  },
  templateDesc: {
    fontSize: 12,
    color: 'var(--text-muted)',
    marginTop: 2,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  templateMeta: {
    fontSize: 11,
    color: 'var(--text-muted)',
    marginTop: 4,
    display: 'flex',
    gap: 4,
  },
  footer: {
    padding: '10px 16px calc(12px + var(--safe-bottom))',
    borderTop: '1px solid var(--border-light)',
    flexShrink: 0,
  },
  confirmBtn: {
    width: '100%',
    minHeight: 46,
    background: 'var(--primary)',
    color: '#fff',
    borderRadius: 10,
    fontSize: 15,
    fontWeight: 600,
  },
}
