import type React from 'react'

export const styles: Record<string, React.CSSProperties> = {
  widget: {
    width: '100%',
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
    background: 'rgba(255, 255, 255, 0.88)',
    backdropFilter: 'blur(20px)',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    overflow: 'hidden',
    borderRadius: 14,
    border: '1px solid rgba(255, 255, 255, 0.45)',
  },
  topBar: {
    display: 'flex',
    alignItems: 'center',
    padding: '9px 12px',
    borderBottom: '1px solid rgba(0, 0, 0, 0.05)',
    gap: 8,
    flexShrink: 0,
  },
  connDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    background: '#34d399',
    flexShrink: 0,
  },
  projectSelect: {
    fontSize: 11,
    fontWeight: 600,
    color: '#374151',
    background: 'rgba(0, 0, 0, 0.04)',
    border: 'none',
    borderRadius: 5,
    padding: '3px 8px',
    cursor: 'pointer',
    flex: 1,
    minWidth: 0,
    outline: 'none',
  },
  btns: {
    display: 'flex',
    gap: 3,
  },
  topBtn: {
    width: 22,
    height: 22,
    border: 'none',
    background: 'none',
    color: '#6b7280',
    cursor: 'pointer',
    borderRadius: 4,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabs: {
    display: 'flex',
    padding: '0 12px',
    borderBottom: '1px solid rgba(0, 0, 0, 0.05)',
    flexShrink: 0,
  },
  tab: {
    fontSize: 11,
    color: '#9ca3af',
    padding: '7px 0',
    marginRight: 16,
    cursor: 'pointer',
    borderBottom: '2px solid transparent',
    fontWeight: 500,
    display: 'flex',
    alignItems: 'center',
    gap: 4,
  },
  tabActive: {
    color: '#1f2937',
    fontWeight: 600,
    borderBottomColor: '#374151',
  },
  tabCnt: {
    fontSize: 9,
    background: 'rgba(0, 0, 0, 0.06)',
    color: '#6b7280',
    padding: '0 4px',
    borderRadius: 6,
    fontWeight: 600,
  },
  tabCntActive: {
    background: '#374151',
    color: 'white',
  },
  panelScroll: {
    flex: 1,
    overflowY: 'auto',
    minHeight: 0,
    padding: '4px 6px',
  },
  empty: {
    color: '#9ca3af',
    fontSize: 11,
    textAlign: 'center',
    padding: '24px 0',
  },
  agentRow: {
    display: 'flex',
    alignItems: 'center',
    padding: '7px 8px',
    borderRadius: 7,
    cursor: 'pointer',
    gap: 9,
  },
  agentIcon: {
    width: 26,
    height: 26,
    borderRadius: 6,
    background: 'rgba(0, 0, 0, 0.04)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    position: 'relative',
    color: '#374151',
  },
  liveDot: {
    position: 'absolute',
    top: -2,
    right: -2,
    width: 7,
    height: 7,
    borderRadius: '50%',
    background: '#22c55e',
    border: '1.5px solid rgba(255, 255, 255, 0.9)',
  },
  unreadDot: {
    position: 'absolute',
    top: -2,
    right: -2,
    width: 7,
    height: 7,
    borderRadius: '50%',
    background: '#3b82f6',
    border: '1.5px solid rgba(255, 255, 255, 0.9)',
  },
  agentBody: {
    flex: 1,
    minWidth: 0,
  },
  agentTitleRow: {
    display: 'flex',
    alignItems: 'baseline',
    gap: 5,
  },
  agentName: {
    fontSize: 12,
    fontWeight: 600,
    color: '#1f2937',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  agentProject: {
    fontSize: 10,
    color: '#9ca3af',
    flexShrink: 0,
  },
  sessionTitle: {
    fontSize: 11,
    color: '#374151',
    marginTop: 1,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  agentDesc: {
    fontSize: 10,
    color: '#9ca3af',
    marginTop: 1,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  unreadText: {
    color: '#2563eb',
    fontWeight: 600,
  },
  agentTime: {
    fontSize: 10,
    color: '#9ca3af',
    flexShrink: 0,
    fontVariantNumeric: 'tabular-nums',
  },
  taskPanel: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
  },
  taskFilters: {
    display: 'flex',
    gap: 0,
    padding: '4px 12px 2px',
    flexShrink: 0,
  },
  taskFilterBtn: {
    fontSize: 10,
    color: '#9ca3af',
    border: 'none',
    background: 'none',
    cursor: 'pointer',
    padding: '3px 8px',
    borderRadius: 4,
    fontWeight: 500,
  },
  taskFilterBtnActive: {
    background: 'rgba(0, 0, 0, 0.06)',
    color: '#1f2937',
    fontWeight: 600,
  },
  taskRow: {
    display: 'flex',
    alignItems: 'center',
    padding: '6px 8px',
    borderRadius: 7,
    gap: 8,
  },
  taskStatus: {
    width: 14,
    height: 14,
    border: '1.5px solid #c8cdd5',
    borderRadius: '50%',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskStatusDot: {
    width: 5,
    height: 5,
    borderRadius: '50%',
    background: '#2563eb',
  },
  taskBody: {
    flex: 1,
    minWidth: 0,
  },
  taskTitle: {
    fontSize: 12,
    color: '#374151',
    lineHeight: '1.3',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  taskMetaRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 5,
    marginTop: 1,
  },
  taskBadge: {
    fontSize: 10,
    fontWeight: 600,
  },
  taskAgent: {
    fontSize: 10,
    color: '#9ca3af',
  },
  quickCreate: {
    padding: '8px 10px',
    borderTop: '1px solid rgba(0, 0, 0, 0.04)',
    flexShrink: 0,
    display: 'flex',
    gap: 5,
    alignItems: 'center',
  },
  quickInput: {
    flex: 1,
    height: 28,
    border: '1px solid rgba(0, 0, 0, 0.08)',
    borderRadius: 6,
    padding: '0 8px',
    fontSize: 11,
    color: '#374151',
    outline: 'none',
    background: 'rgba(255, 255, 255, 0.6)',
    minWidth: 0,
  },
  agentPick: {
    fontSize: 10,
    color: '#6b7280',
    border: '1px solid rgba(0, 0, 0, 0.08)',
    borderRadius: 5,
    padding: '0 6px',
    height: 28,
    background: 'rgba(255, 255, 255, 0.5)',
    cursor: 'pointer',
    maxWidth: 92,
  },
  createBtn: {
    width: 28,
    height: 28,
    border: 'none',
    background: '#374151',
    color: 'white',
    borderRadius: 6,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
}
