import type { CreateToolInput } from '../store/tools.js'

const AGENT_SESSION_PERMISSIONS = { requiresApproval: false, maxExecutionTime: 10_000, networkAccess: false }

export const AGENT_SESSION_BUILTIN_TOOLS: (CreateToolInput & { defaultScope: 'global' })[] = [
  {
    name: 'agent.message.send',
    displayName: '发送 Agent 消息',
    description: '向另一个 Agent 会话发送消息。异步投递，调用后立即返回，不要等待目标 Agent 完成。\n\ntargetSessionId 建议:\n- 回复对方消息时:填对方系统消息里的"来源会话 ID",确保回复进原上下文\n- 主动发起对话时:填对方 primary 会话 ID(可用 agent.session.list 查)\n- 仅首次联系对方、对方没有任何活跃会话时,才只传 targetAgentId 新建会话\n- 已有活跃会话但只传 targetAgentId,会新建空壳会话,对方很可能看不到\n\n如果 needReply=true,发送后结束当前轮;目标 Agent 回传后系统会自动唤醒来源会话。',
    category: 'automation',
    type: 'builtin',
    config: { handler: 'agent.message.send' },
    inputSchema: {
      type: 'object',
      properties: {
        targetAgentId: { type: 'string', description: '目标 Agent ID。通常和 targetSessionId 一起传;仅在首次联系对方且无活跃会话时单独传,会新建会话' },
        targetSessionId: { type: 'string', description: '目标会话 ID。回复对方消息时填对方系统消息里的"来源会话 ID";主动发起对话时填对方 primary 会话 ID。除非是首次联系对方且无活跃会话,否则建议总是传入,避免消息落到空壳会话' },
        content: { type: 'string', description: '消息内容' },
        relatedInfo: { type: 'object', description: '动态关联信息 JSON' },
        needReply: { type: 'boolean', description: '是否要求目标 Agent 完成后回复；系统会在收到回复后自动唤醒来源会话' },
      },
      required: ['content'],
    },
    permissions: AGENT_SESSION_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'agent.session.list',
    displayName: '查看 Agent 会话',
    description: '查看某个 Agent 在当前项目内的会话列表。',
    category: 'data',
    type: 'builtin',
    config: { handler: 'agent.session.list' },
    inputSchema: {
      type: 'object',
      properties: {
        agentId: { type: 'string', description: 'Agent ID' },
        limit: { type: 'number', description: '返回数量，默认 20' },
      },
      required: ['agentId'],
    },
    permissions: AGENT_SESSION_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'agent.session.messages',
    displayName: '查看会话消息',
    description: '查看某个会话的最近消息。',
    category: 'data',
    type: 'builtin',
    config: { handler: 'agent.session.messages' },
    inputSchema: {
      type: 'object',
      properties: {
        sessionId: { type: 'string', description: '会话 ID' },
        limit: { type: 'number', description: '返回数量，默认 10' },
      },
      required: ['sessionId'],
    },
    permissions: AGENT_SESSION_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'agent.session.watch',
    displayName: '监听会话完成',
    description: '一次性监听另一个会话的完成事件。被监听会话执行完一轮后,系统自动唤醒你的会话。单次触发后自动失效,不支持取消。',
    category: 'automation',
    type: 'builtin',
    config: { handler: 'agent.session.watch' },
    inputSchema: {
      type: 'object',
      properties: {
        sessionId: { type: 'string', description: '被监听会话 ID' },
        relatedInfo: { type: 'object', description: '动态关联信息 JSON' },
      },
      required: ['sessionId'],
    },
    permissions: AGENT_SESSION_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'agent.task.watch',
    displayName: '监听任务状态',
    description: '持续性监听一个任务。触发时机:步骤 done / 步骤 blocked / 任务 completed / 任务回退到 draft。updateProgress/milestone/ready/pending 不触发。需要用 agent.task.watch.cancel 取消。',
    category: 'automation',
    type: 'builtin',
    config: { handler: 'agent.task.watch' },
    inputSchema: {
      type: 'object',
      properties: {
        taskId: { type: 'string', description: '被监听任务 ID' },
        relatedInfo: { type: 'object', description: '动态关联信息 JSON' },
      },
      required: ['taskId'],
    },
    permissions: AGENT_SESSION_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'agent.task.watch.cancel',
    displayName: '取消任务监听',
    description: '取消 agent.task.watch 创建的监听。',
    category: 'automation',
    type: 'builtin',
    config: { handler: 'agent.task.watch.cancel' },
    inputSchema: {
      type: 'object',
      properties: { watchId: { type: 'string', description: 'Watch ID' } },
      required: ['watchId'],
    },
    permissions: AGENT_SESSION_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'agent.wake_me',
    displayName: '定时唤醒自己',
    description: '一次性唤醒自己:到指定延迟后,系统会把 tips 注入到当前会话。基于 schedule 规则引擎实现,maxRuns=1 自动失效,不支持取消。',
    category: 'automation',
    type: 'builtin',
    config: { handler: 'agent.wake_me' },
    inputSchema: {
      type: 'object',
      properties: {
        delay_seconds: { type: 'number', description: '延迟秒数,最小 60(因为 cron 引擎按分钟粒度匹配)' },
        tips: { type: 'string', description: '唤醒时注入到当前会话的提示内容' },
      },
      required: ['delay_seconds', 'tips'],
    },
    permissions: AGENT_SESSION_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
]
