import type { CreateToolInput } from '../store/tools.js'

const EVENT_PERMISSIONS = { requiresApproval: false, maxExecutionTime: 10_000, networkAccess: false }

export const EVENT_CENTER_BUILTIN_TOOLS: (CreateToolInput & { defaultScope: 'global' })[] = [
  {
    name: 'event.category.list',
    displayName: '列出事件类别',
    description: '列出当前 Agent 可见的事件类别和 payload schema 提示。',
    category: 'data',
    type: 'builtin',
    config: { handler: 'event.category.list' },
    inputSchema: { type: 'object', properties: {} },
    permissions: EVENT_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'event.category.create',
    displayName: 'Create event category',
    description: 'Create a new event center category. Fails if categoryId already exists; use event.category.update to modify an existing category.',
    category: 'automation',
    type: 'builtin',
    config: { handler: 'event.category.create' },
    inputSchema: {
      type: 'object',
      properties: {
        categoryId: { type: 'string', description: 'Event category ID, for example custom.alert' },
        name: { type: 'string', description: 'Display name' },
        description: { type: 'string', description: 'Category description' },
        schema: { type: 'object', description: 'Payload schema hint for events in this category' },
        defaultPriority: { type: 'string', description: 'Default priority, for example low/medium/high' },
        allowedWriters: { type: 'array', items: { type: 'string' }, description: 'Agent IDs or agent types allowed to write; omit to allow all' },
        allowedConsumers: { type: 'array', items: { type: 'string' }, description: 'Agent IDs or agent types allowed to consume; omit to allow all' },
        enabled: { type: 'boolean', description: 'Whether the category is enabled; defaults to true' },
      },
      required: ['categoryId', 'name'],
    },
    permissions: EVENT_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'event.category.update',
    displayName: 'Update event category',
    description: 'Partially update an existing event center category. Fields not provided are preserved.',
    category: 'automation',
    type: 'builtin',
    config: { handler: 'event.category.update' },
    inputSchema: {
      type: 'object',
      properties: {
        categoryId: { type: 'string', description: 'Existing event category ID' },
        name: { type: 'string', description: 'Display name' },
        description: { type: 'string', description: 'Category description' },
        schema: { type: 'object', description: 'Payload schema hint for events in this category' },
        defaultPriority: { type: 'string', description: 'Default priority, for example low/medium/high' },
        allowedWriters: { type: 'array', items: { type: 'string' }, description: 'Agent IDs or agent types allowed to write' },
        allowedConsumers: { type: 'array', items: { type: 'string' }, description: 'Agent IDs or agent types allowed to consume' },
        enabled: { type: 'boolean', description: 'Whether the category is enabled' },
      },
      required: ['categoryId'],
    },
    permissions: EVENT_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'event.create',
    displayName: '写入事件',
    description: '向事件中心写入一条分类事件。',
    category: 'automation',
    type: 'builtin',
    config: { handler: 'event.create' },
    inputSchema: {
      type: 'object',
      properties: {
        projectId: { type: 'string' },
        categoryId: { type: 'string' },
        title: { type: 'string' },
        summary: { type: 'string' },
        priority: { type: 'string' },
        confidence: { type: 'number' },
        tags: { type: 'array', items: { type: 'string' } },
        payload: { type: 'object' },
        evidence: { type: 'array', items: { type: 'object' } },
        dedupeKey: { type: 'string' },
      },
      required: ['categoryId', 'title'],
    },
    permissions: EVENT_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'event.list',
    displayName: '查询事件',
    description: '查询事件中心事件，可按类别、状态和项目过滤。',
    category: 'data',
    type: 'builtin',
    config: { handler: 'event.list' },
    inputSchema: {
      type: 'object',
      properties: {
        projectId: { type: 'string' },
        categoryId: { type: 'string' },
        status: { type: 'string' },
      },
    },
    permissions: EVENT_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'event.get',
    displayName: '查看事件',
    description: '查看事件详情和消费记录。',
    category: 'data',
    type: 'builtin',
    config: { handler: 'event.get' },
    inputSchema: {
      type: 'object',
      properties: { eventId: { type: 'string' } },
      required: ['eventId'],
    },
    permissions: EVENT_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'event.claim_next',
    displayName: '领取事件',
    description: '领取当前 Agent 订阅的下一个待消费事件。',
    category: 'automation',
    type: 'builtin',
    config: { handler: 'event.claim_next' },
    inputSchema: { type: 'object', properties: { projectId: { type: 'string' } } },
    permissions: EVENT_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'event.consume',
    displayName: '提交消费结果',
    description: '提交事件消费结果。',
    category: 'automation',
    type: 'builtin',
    config: { handler: 'event.consume' },
    inputSchema: {
      type: 'object',
      properties: {
        consumptionId: { type: 'string' },
        resultSummary: { type: 'string' },
        result: { type: 'object' },
        error: { type: 'string' },
      },
      required: ['consumptionId'],
    },
    permissions: EVENT_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'event.convert_to_task',
    displayName: '事件转任务',
    description: '把事件中心事件转成普通任务。',
    category: 'automation',
    type: 'builtin',
    config: { handler: 'event.convert_to_task' },
    inputSchema: {
      type: 'object',
      properties: {
        eventId: { type: 'string' },
        title: { type: 'string' },
        description: { type: 'string' },
        assignAgentId: { type: 'string' },
        projectId: { type: 'string' },
      },
      required: ['eventId'],
    },
    permissions: EVENT_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'event.ignore',
    displayName: '忽略事件',
    description: '忽略事件中心事件。',
    category: 'automation',
    type: 'builtin',
    config: { handler: 'event.ignore' },
    inputSchema: {
      type: 'object',
      properties: { eventId: { type: 'string' } },
      required: ['eventId'],
    },
    permissions: EVENT_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'event.subscription.create',
    displayName: '创建事件订阅',
    description: '创建事件订阅规则，定义哪个 Agent 消费哪类事件。filter 顶层仅支持 minConfidence、priority、sourceType、payload；事件 payload 字段必须放入 filter.payload，例如 task.lifecycle 待办任务使用 {"payload":{"taskStatus":"backlog"}}。',
    category: 'automation',
    type: 'builtin',
    config: { handler: 'event.subscription.create' },
    inputSchema: {
      type: 'object',
      properties: {
        projectId: { type: 'string' },
        name: { type: 'string' },
        categoryId: { type: 'string' },
        consumerAgentId: { type: 'string' },
        consumerLabel: { type: 'string' },
        actionMode: { type: 'string' },
        filter: {
          type: 'object',
          description: '订阅过滤条件。顶层支持 minConfidence、priority、sourceType、payload。payload 是事件 payload 字段过滤，如 {"payload":{"taskStatus":"backlog","assignedAgentId":null}}；不要传扁平 {"taskStatus":"backlog"}。',
          properties: {
            minConfidence: { type: 'number', description: '最低置信度，0-1' },
            priority: { type: 'string', description: '事件优先级，如 low/medium/high' },
            sourceType: { type: 'string', description: '事件来源类型' },
            payload: {
              type: 'object',
              description: '事件 payload 字段过滤。值可为直接值、null、{"in":[...]}, 或 {"exists":true/false}。',
            },
          },
        },
        autoStart: { type: 'boolean' },
        consumerSessionMode: { type: 'string', enum: ['existing', 'new_each', 'new_fixed'] },
        consumerSessionId: { type: 'string' },
      },
      required: ['name', 'categoryId'],
    },
    permissions: EVENT_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
]
