import type { CreateToolInput } from '../store/tools.js'

const KB_PERMISSIONS = { requiresApproval: false, maxExecutionTime: 10_000, networkAccess: false }

export const KB_BUILTIN_TOOLS: (CreateToolInput & { defaultScope: 'global' })[] = [
  {
    name: 'core.kb.list',
    displayName: 'List knowledge bases',
    description: 'List the knowledge bases visible to the current project.',
    category: 'data',
    type: 'builtin',
    config: { handler: 'core.kb.list' },
    inputSchema: { type: 'object', properties: { projectId: { type: 'string', description: 'Project ID' } } },
    permissions: KB_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'core.kb.read_index',
    displayName: 'Read KB index',
    description: 'Read a knowledge base index page before deciding which pages to inspect.',
    category: 'data',
    type: 'builtin',
    config: { handler: 'core.kb.read_index' },
    inputSchema: {
      type: 'object',
      properties: {
        projectId: { type: 'string', description: 'Project ID' },
        kbId: { type: 'string', description: 'Knowledge base ID' },
      },
      required: ['kbId'],
    },
    permissions: KB_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'core.kb.read_page',
    displayName: 'Read KB page',
    description: 'Read a markdown knowledge page by page id or by title within a knowledge base.',
    category: 'data',
    type: 'builtin',
    config: { handler: 'core.kb.read_page' },
    inputSchema: {
      type: 'object',
      properties: {
        projectId: { type: 'string', description: 'Project ID' },
        pageId: { type: 'string', description: 'Page ID' },
        kbId: { type: 'string', description: 'Knowledge base ID' },
        title: { type: 'string', description: 'Page title' },
      },
    },
    permissions: KB_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'core.kb.search',
    displayName: 'Search KB',
    description: 'Search visible knowledge pages using title, summary, and body text.',
    category: 'data',
    type: 'builtin',
    config: { handler: 'core.kb.search' },
    inputSchema: {
      type: 'object',
      properties: {
        projectId: { type: 'string', description: 'Project ID' },
        query: { type: 'string', description: 'Search query' },
        kbIds: { type: 'array', items: { type: 'string' }, description: 'Optional KB ID filter' },
        limit: { type: 'number', description: 'Maximum result count' },
      },
      required: ['query'],
    },
    permissions: KB_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'core.kb.create_page',
    displayName: 'Create KB page',
    description: 'Create a markdown knowledge page and record an activity entry.',
    category: 'data',
    type: 'builtin',
    config: { handler: 'core.kb.create_page' },
    inputSchema: {
      type: 'object',
      properties: {
        projectId: { type: 'string', description: 'Project ID' },
        kbId: { type: 'string', description: 'Knowledge base ID' },
        title: { type: 'string', description: 'Page title' },
        section: { type: 'string', description: 'Page section' },
        summary: { type: 'string', description: 'Short page summary' },
        body: { type: 'string', description: 'Markdown body' },
        tags: { type: 'array', items: { type: 'string' }, description: 'Tags' },
        srcFiles: { type: 'array', items: { type: 'string' }, description: 'Source files for code pages' },
        note: { type: 'string', description: 'Activity note' },
      },
      required: ['kbId', 'title', 'body'],
    },
    permissions: KB_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'core.kb.update_page',
    displayName: 'Update KB page',
    description: 'Update a markdown knowledge page and record an activity entry.',
    category: 'data',
    type: 'builtin',
    config: { handler: 'core.kb.update_page' },
    inputSchema: {
      type: 'object',
      properties: {
        projectId: { type: 'string', description: 'Project ID' },
        pageId: { type: 'string', description: 'Page ID' },
        title: { type: 'string', description: 'New title' },
        section: { type: 'string', description: 'New section' },
        summary: { type: 'string', description: 'New summary' },
        body: { type: 'string', description: 'Markdown body' },
        tags: { type: 'array', items: { type: 'string' }, description: 'Tags' },
        note: { type: 'string', description: 'Activity note' },
      },
      required: ['pageId', 'body'],
    },
    permissions: KB_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'core.kb.refresh_from_code',
    displayName: 'Refresh KB from code',
    description: 'Refresh a code-sourced page after reading the current source files.',
    category: 'code',
    type: 'builtin',
    config: { handler: 'core.kb.refresh_from_code' },
    inputSchema: {
      type: 'object',
      properties: {
        projectId: { type: 'string', description: 'Project ID' },
        pageId: { type: 'string', description: 'Page ID' },
        body: { type: 'string', description: 'Updated markdown body' },
        srcFiles: { type: 'array', items: { type: 'string' }, description: 'Source files' },
        confirmOverwriteHumanEdit: { type: 'boolean', description: 'Confirm overwriting a human edit' },
        note: { type: 'string', description: 'Activity note' },
      },
      required: ['pageId', 'body'],
    },
    permissions: KB_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'core.kb.create_kb',
    displayName: 'Create KB',
    description: 'Create a project or shared knowledge base.',
    category: 'data',
    type: 'builtin',
    config: { handler: 'core.kb.create_kb' },
    inputSchema: {
      type: 'object',
      properties: {
        projectId: { type: 'string', description: 'Project ID for project KBs' },
        name: { type: 'string', description: 'Knowledge base name' },
        kind: { type: 'string', enum: ['project', 'shared'], description: 'Knowledge base kind' },
        src: { type: 'string', enum: ['manual', 'code'], description: 'Knowledge source type' },
        icon: { type: 'string', description: 'Icon' },
        description: { type: 'string', description: 'Description' },
        note: { type: 'string', description: 'Activity note' },
      },
      required: ['name', 'kind', 'src'],
    },
    permissions: KB_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'core.kb.mount',
    displayName: 'Mount KB',
    description: 'Mount a shared knowledge base into the current project.',
    category: 'data',
    type: 'builtin',
    config: { handler: 'core.kb.mount' },
    inputSchema: {
      type: 'object',
      properties: {
        projectId: { type: 'string', description: 'Project ID' },
        kbId: { type: 'string', description: 'Knowledge base ID' },
        note: { type: 'string', description: 'Activity note' },
      },
      required: ['kbId'],
    },
    permissions: KB_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'core.kb.unmount',
    displayName: 'Unmount KB',
    description: 'Unmount a shared knowledge base from the current project.',
    category: 'data',
    type: 'builtin',
    config: { handler: 'core.kb.unmount' },
    inputSchema: {
      type: 'object',
      properties: {
        projectId: { type: 'string', description: 'Project ID' },
        kbId: { type: 'string', description: 'Knowledge base ID' },
        note: { type: 'string', description: 'Activity note' },
      },
      required: ['kbId'],
    },
    permissions: KB_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
  {
    name: 'core.kb.revert',
    displayName: 'Revert KB activity',
    description: 'Revert a previous knowledge base activity.',
    category: 'data',
    type: 'builtin',
    config: { handler: 'core.kb.revert' },
    inputSchema: {
      type: 'object',
      properties: {
        projectId: { type: 'string', description: 'Project ID' },
        activityId: { type: 'string', description: 'Activity ID' },
        note: { type: 'string', description: 'Activity note' },
      },
      required: ['activityId'],
    },
    permissions: KB_PERMISSIONS,
    isBuiltin: true,
    defaultScope: 'global',
  },
]
